# Generated by Django 6.0.3 on 2026-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_description_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_bn',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='phone_jay',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_primary',
            field=models.CharField(default='6202822415', max_length=20, verbose_name='Phone (Satyan Jha)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone_secondary',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='Darbhanga, Mithila, Bihar'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Mithila White Gold', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='landmark',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='मिथिला की धरोहर — हर कौर में।', max_length=300),
        ),
    ]
