# Generated by Django 6.0.3 on 2026-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sitesettings_phone_bn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='products/videos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Or provide a YouTube/Vimeo video URL', null=True),
        ),
    ]
