# Generated by Django 6.0.3 on 2026-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_video_file_product_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video',
            field=models.FileField(blank=True, help_text='Advertisement video for homepage', null=True, upload_to='site/videos/'),
        ),
    ]
