# Generated by Django 6.0.3 on 2026-05-03 08:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sitesettings_promo_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_content', models.BinaryField()),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Dynamic Media',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='image_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_main_image', to='store.dynamicmedia'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_video_file', to='store.dynamicmedia'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_image', to='store.dynamicmedia'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='promo_video_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_promo_video', to='store.dynamicmedia'),
        ),
    ]
