# Generated by Django 6.0.3 on 2026-05-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_salesrecord_seller_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
