# Generated by Django 6.0.3 on 2026-06-06 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_pic_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profile_pic', to='store.dynamicmedia'),
        ),
    ]
